### ISSUE TITLE
Add a 'gameover' screen

### ISSUE THREAD

**Issue by jazariethach** [UCSB-CS56-Projects/cs56-games-towers-of-hanoi#25]
It isn't obvious when the player loses the game. Make a gameover screen pop up.

**Comment by emorozova** [comment]
Does "losing the game" mean not completing it in the optimum number of moves? Since the game ends only when the tower has been moved, how would we know when the player loses the game?

**Comment by jazariethach** [comment]
Sorry this issue was meant for another project, my bad!
