### ISSUE TITLE
Change GUI appearance

### ISSUE THREAD

**Issue by matthewcheung8** [UCSB-CS56-Projects/cs56-games-towers-of-hanoi#42]
Reorganize JFrame so components fit/look better. 100 points

**Comment by ashedden** [comment]
W16 ok!

**Comment by jalexanderqed** [comment]
This could include spreading out the display of disks depending on the height of the stack since for large numbers of disks, the towers appear squashed.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)
