### ISSUE TITLE
Create an Options button

### ISSUE THREAD

**Issue by matthewcheung8** [UCSB-CS56-Projects/cs56-games-towers-of-hanoi#45]
This is because it will make the Game GUI look nicer. Options button would take the users to a separate frame/panel that shows the pause or reset button. 
150 points

**Comment by ashedden** [comment]
W16 ok!

**Comment by jalexanderqed** [comment]
Up to you whether to implement this. I don't see how it would improve the look of the game, but up to you.

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)
