### ISSUE TITLE
Create a options menu

### ISSUE THREAD

**Issue by metomario** [UCSB-CS56-Projects/cs56-games-towers-of-hanoi#48]
Create a options menu in the title screen that the player can turn off the instructions. 
Make it so that the choice is saved (possibly through serializable) and is loaded the next time the game runs.

Est. 150 pts.

**Comment by ashedden** [comment]
W16 ok!

**Comment by jalexanderqed** [comment]
F16 OK (100 pts)

**Comment by jalexanderqed** [comment]
If options are turned off, could you please also skip the screen after clicking "Play" that explains the game? It would be nice not to have to go through it every time. Also, the current solution to this problem should be abstracted into a separate class. It adds too much unrelated code to `GUIMain.java` that really clutters up the file.
