### ISSUE TITLE
Save Game State

### ISSUE THREAD

**Issue by ttsherpa1996** [UCSB-CS56-Projects/cs56-games-towers-of-hanoi#59]
Adding a save button to the Game Frame allows user to save his or her game state. So later if user wanted to continue on with the same game state he or she can access that game state through the press of a continue button in the main frame. 

estimated = 200 points

**Comment by pconrad** [comment]
I have a question.  Is the intention only to 'pause' the game? Or would the game state be saved to a file on the disk?

Would you use Java serialization to do this or some other way of saving the state?

**Comment by wdlzz926** [comment]
@pconrad The game state will be save to a file using Java serialization. The player can resume the game after he or she close the game.

**Comment by jalexanderqed** [comment]
F16 OK (150 pts)
