### ISSUE TITLE
Move count not reseted when playing again or continuing from save

### ISSUE THREAD

**Issue by YunSuk** [UCSB-CS56-Projects/cs56-games-towers-of-hanoi#69]
Move count GUI label is not updated/reseted in the beginning when player is continuing from last save or playing again.

**Comment by EasterAndJay** [comment]
How many points is this issue worth?

**Comment by YunSuk** [comment]
100 points

**Comment by YunSuk** [comment]
Move count GUI label is correct when user saves and quits the game and then continues the game.  

However, when user saves and quits the game and press play button, move count is not updated. Also, when user quits the game (as in close the program), re-runs the game, and then continues the game, the move count is not updated.

This bug is more complicated than 100 points. Will reopen a separate issue for the bug
